server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://localhost:3306/productdb
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/