services:
    web: 
        image: nginx
        ports: 
         - "8080:80"
    db: 
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_test
        ports:
         - "3306:3306"
       